name:  swagger-ui x InvisiRisk 

on:
  schedule:
    - cron: '15 0 * * 1'  # every Monday morning
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "ir-pranesh-shrestha"
          git config user.email "pranesh.shrestha@invisirisk.com"
      - name: Add upstream and sync fork
        run: |
          git remote add upstream https://github.com/swagger-api/swagger-ui.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-edit
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/ir-pranesh-shrestha/swagger-ui master
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"


  
  gather_analytics:
    runs-on: ubuntu-latest
    name: Gather Analytics
    needs: sync-and-build
    if: always()
    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          send_job_status: "true"
          debug: "true"

